### ISSUE TITLE
关于邮箱

### ISSUE THREAD

**Issue by SITUSITU** [chunmeifeng/T2Net#17]
您好，我有一些问题想请教，但您论文里提供的邮箱 {strawberry.feng0304}@gmail.com 我尝试了好多次都无法发送邮件。请问您是换了邮箱地址吗？还是这个邮箱有一些符号要删减

**Comment by chunmeifeng** [comment]
没有

SITUSITU ***@***.***>于2023年1月29日 周日上午8:04写道：

**Comment by SITUSITU** [comment]
那么请问您现在的邮箱地址是什么呢？我尝试往 feng0304@gmail.com 发送邮件但显示找不到邮箱地址

**Comment by chunmeifeng** [comment]
请使用我现在的邮箱

SITUSITU ***@***.***>于2023年1月29日 周日下午8:02写道：
