### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Aristot1e** [chunmeifeng/T2Net#4]
About the IXI Dataset, it's .nii file. Should I transform it to .h5 or .mat file? And what should I do if I need to?

**Comment by chunmeifeng** [comment]
Hi, you need to transform the .nii file to .mat file at first, we will provide this code soon.

**Comment by chunmeifeng** [comment]
> 
Hi, you need to transform the .nii file to .mat file at first, we will provide this code soon.

**Comment by chunmeifeng** [comment]
> 
Hi, you need to transform the .nii file to .mat file at first, we will provide this code soon.


> About the IXI Dataset, it's .nii file. Should I transform it to .h5 or .mat file? And what should I do if I need to?


We have provided the code of converting the .nii file to .mat file as well as the .mat data.
Please find the updated file.
